class Parameters:
    FPS = 4
    FREQ = 1.0 / FPS
    GAMMA = 0.95
    ALPHA = 0.2
    LAMBDA = 0.35
    EPS = 0.09
    DEFAULT_ELIGIBILITY = 0
    DEFAULT_QVALUE = 0
    INC_ELIGIBILITY = 1
    INF = 1e9
    LEARN_EPOCHS = 50
    EPISODES_PER_EPOCH = 100
    MAX_LEN_EPISODE = 70
